### ISSUE TITLE
diff from NVlabs / NVAE ?

### ISSUE THREAD

**Issue by iperov** [ericl122333/latent-vae#1]
looks similar
https://github.com/NVlabs/NVAE

**Comment by ericl122333** [comment]
Hi, 

While NVAE is a notable VAE, our implementation is primarily based on [VDVAE](https://github.com/openai/vdvae), which among other things, differs from NVAE by not using batchnorm, depthwise convs, and squeeze-excitation. Compared to VDVAE, our model has a different output layer (gaussian instead of DMOL), a KL-scheduling technique to prevent posterior collapse, and crucially, a first-stage autoencoder like that of [LDM](https://github.com/CompVis/latent-diffusion) since we found training in latent space much better given a fixed compute constraint. Also our models support classifier-free guidance (unlike NVAE/VDVAE), which we found also improved performance greatly on imagenet.

Thanks,
Eric
